[project]
channels = ["conda-forge", "r", "main"]
description = "A demo project using quarto and pixi for full-stack reproducibility"
name = "rypyr"
platforms = ["linux-64", "win-64", "osx-64"] # I left osx-arm because theres no r-satellite <https://pixi.sh/v0.27.1/reference/project_configuration/#the-project-table>
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12"
jupyter = "*"
jupyterlab = "*"
ipywidgets = "*"
jupyterlab_widgets = "*"
pandas = ">=1.0"
quarto = "*"
watermark = "*"
seaborn = "*"
ipyleaflet = "*"
geosnap = "*"
pysal = "*"
streamlit = "*"
gh = "*"
openpyxl = "*"
geopy = "*"
holoviews = "*"
hvplot = "*"
pyarrow = "*"
lonboard = "*"
h3-py = "*"
rpy2 = "*"
# R deps
r-irkernel = "*"
r-tidymodels = "*"
#r-spdep = "*" # sfdep hasn't made it onto conda-forge yet
r-nlme = "*"
r-lme4 = "*"
r-tidycensus = "*"
r-tigris = "*"
r-reticulate = "*"
r-mapview = "*" 
r-languageserver = "*"
