project:
  type: manuscript
  render:
    - "../notebooks/"
    - "*.qmd"

manuscript:
  article: index.qmd

format:
  pdf:
    output-file: rypyrx
  html: 
    output-file: rypyrx
execute:
  echo: true
  cache: true
jupyter: python3