project:
  type: manuscript
  output-dir: ../output
  render:
    - "../notebooks/"
    - "*.qmd"

manuscript:
  article: index.qmd

format:
  pdf:
    output-file: rypyr
  html:     
    embed-resources: true

execute:
  echo: true
jupyter: python3