project:
  type: manuscript
  output-dir: ../output
  render:
    - "../notebooks/"
    - "*.qmd"

manuscript:
  article: index.qmd

format:
  pdf:
    output-file: rypyr
  html: default
execute:
  echo: true
  cache: true
jupyter: python3